// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: count_transactions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions t
JOIN accounts a ON t.account_id = a.id
WHERE a.user_id = $1
  AND ($2::uuid IS NULL OR t.account_id = $2)
  AND ($3::uuid IS NULL OR t.category_id = $3)
  AND ($4::timestamptz IS NULL OR t.occurred_at >= $4)
  AND ($5::timestamptz IS NULL OR t.occurred_at <= $5)
`

type CountTransactionsParams struct {
	UserID     uuid.UUID
	AccountID  uuid.NullUUID
	CategoryID uuid.NullUUID
	FromDate   sql.NullTime
	ToDate     sql.NullTime
}

func (q *Queries) CountTransactions(ctx context.Context, arg CountTransactionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransactions,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}
