// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_budget.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1 AND user_id = $2
`

type DeleteBudgetParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteBudget(ctx context.Context, arg DeleteBudgetParams) error {
	_, err := q.db.ExecContext(ctx, deleteBudget, arg.ID, arg.UserID)
	return err
}
