// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: delete_category.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const archiveCategory = `-- name: ArchiveCategory :exec
UPDATE categories
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND archived_at IS NULL
`

type ArchiveCategoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ArchiveCategory(ctx context.Context, arg ArchiveCategoryParams) error {
	_, err := q.db.ExecContext(ctx, archiveCategory, arg.ID, arg.UserID)
	return err
}
