// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCategories = `-- name: GetCategories :many
SELECT id, name, created_at, type, user_id, archived_at FROM categories WHERE user_id = $1 AND archived_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetCategories(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, getCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Type,
			&i.UserID,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
