// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_account.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAccount = `-- name: GetAccount :one
SELECT id, name, created_at, starting_balance, type, user_id FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.StartingBalance,
		&i.Type,
		&i.UserID,
	)
	return i, err
}
