// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_category.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getCategory = `-- name: GetCategory :one
SELECT id, name, created_at, type, user_id, archived_at FROM categories
WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Type,
		&i.UserID,
		&i.ArchivedAt,
	)
	return i, err
}
