// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_account_spent.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getTotalExpenseAmount = `-- name: GetTotalExpenseAmount :one
SELECT 
    COALESCE(SUM(t.amount), 0)::numeric AS total_expenses
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN categories c ON c.id = t.category_id
WHERE a.user_id = $1 
AND a.id = $2
AND c.type = 'expenses'
`

type GetTotalExpenseAmountParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) GetTotalExpenseAmount(ctx context.Context, arg GetTotalExpenseAmountParams) (decimal.Decimal, error) {
	row := q.db.QueryRowContext(ctx, getTotalExpenseAmount, arg.UserID, arg.ID)
	var total_expenses decimal.Decimal
	err := row.Scan(&total_expenses)
	return total_expenses, err
}
