// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_month_spending.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getMonthlySpending = `-- name: GetMonthlySpending :many
SELECT 
    t.category_id,
    SUM(t.amount)::numeric AS total_spent
FROM transactions t
JOIN accounts a ON a.id = t.account_id
JOIN categories c ON c.id = t.category_id
WHERE a.user_id = $1
AND c.type = 'expenses'
AND TO_CHAR(t.occurred_at, 'YYYY-MM') = $2::text
GROUP BY t.category_id
`

type GetMonthlySpendingParams struct {
	UserID  uuid.UUID
	Column2 string
}

type GetMonthlySpendingRow struct {
	CategoryID uuid.NullUUID
	TotalSpent decimal.Decimal
}

func (q *Queries) GetMonthlySpending(ctx context.Context, arg GetMonthlySpendingParams) ([]GetMonthlySpendingRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlySpending, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySpendingRow
	for rows.Next() {
		var i GetMonthlySpendingRow
		if err := rows.Scan(&i.CategoryID, &i.TotalSpent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
