// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_budgets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getBudgets = `-- name: GetBudgets :many
SELECT id, created_at, monthly_limit, month, user_id, category_id FROM budgets
WHERE user_id = $1
ORDER BY month DESC
`

func (q *Queries) GetBudgets(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.QueryContext(ctx, getBudgets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.MonthlyLimit,
			&i.Month,
			&i.UserID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
