// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getAccounts = `-- name: GetAccounts :many
SELECT id, name, created_at, starting_balance, type, user_id FROM accounts WHERE user_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetAccounts(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.StartingBalance,
			&i.Type,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
