// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transaction.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTransaction = `-- name: GetTransaction :one
SELECT id, amount, created_at, occurred_at, description, account_id, category_id FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.Description,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}
