// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type Account struct {
	ID              uuid.UUID
	Name            string
	CreatedAt       time.Time
	StartingBalance decimal.Decimal
	Type            string
	UserID          uuid.UUID
}

type Budget struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	MonthlyLimit decimal.Decimal
	Month        string
	UserID       uuid.UUID
	CategoryID   uuid.UUID
}

type Category struct {
	ID         uuid.UUID
	Name       string
	CreatedAt  time.Time
	Type       string
	UserID     uuid.UUID
	ArchivedAt sql.NullTime
}

type Transaction struct {
	ID          uuid.UUID
	Amount      decimal.Decimal
	CreatedAt   time.Time
	OccurredAt  time.Time
	Description sql.NullString
	AccountID   uuid.UUID
	CategoryID  uuid.NullUUID
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
}
