// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_account.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1, starting_balance = $2, type = $3
WHERE id = $4
RETURNING id, name, created_at, starting_balance, type, user_id
`

type UpdateAccountParams struct {
	Name            string
	StartingBalance decimal.Decimal
	Type            string
	ID              uuid.UUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.StartingBalance,
		arg.Type,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.StartingBalance,
		&i.Type,
		&i.UserID,
	)
	return i, err
}
