// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_category.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $1, type = $2
WHERE id = $3 AND user_id = $4
RETURNING id, name, created_at, type, user_id
`

type UpdateCategoryParams struct {
	Name   string
	Type   string
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, updateCategory,
		arg.Name,
		arg.Type,
		arg.ID,
		arg.UserID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Type,
		&i.UserID,
	)
	return i, err
}
