// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_account.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, name, starting_balance, type, user_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, name, created_at, starting_balance, type, user_id
`

type CreateAccountParams struct {
	Name            string
	StartingBalance decimal.Decimal
	Type            string
	UserID          uuid.UUID
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.Name,
		arg.StartingBalance,
		arg.Type,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.StartingBalance,
		&i.Type,
		&i.UserID,
	)
	return i, err
}
