// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_transaction.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, amount, occurred_at, description, account_id, category_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, amount, created_at, occurred_at, description, account_id, category_id
`

type CreateTransactionParams struct {
	Amount      string
	OccurredAt  time.Time
	Description sql.NullString
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Amount,
		arg.OccurredAt,
		arg.Description,
		arg.AccountID,
		arg.CategoryID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.Description,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}
