// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: create_budget.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (id, monthly_limit, month, user_id, category_id)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4
)
RETURNING id, created_at, monthly_limit, month, user_id, category_id
`

type CreateBudgetParams struct {
	MonthlyLimit string
	Month        string
	UserID       uuid.UUID
	CategoryID   uuid.UUID
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRowContext(ctx, createBudget,
		arg.MonthlyLimit,
		arg.Month,
		arg.UserID,
		arg.CategoryID,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.MonthlyLimit,
		&i.Month,
		&i.UserID,
		&i.CategoryID,
	)
	return i, err
}
