// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTransactions = `-- name: GetTransactions :many
SELECT id, amount, created_at, occurred_at, description, account_id, category_id FROM transactions 
WHERE account_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsParams struct {
	AccountID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) GetTransactions(ctx context.Context, arg GetTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getTransactions, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.CreatedAt,
			&i.OccurredAt,
			&i.Description,
			&i.AccountID,
			&i.CategoryID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
