// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_budgets_month.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getBudgetsForMonth = `-- name: GetBudgetsForMonth :many
SELECT 
    b.category_id,
    c.name AS category_name,
    b.monthly_limit
FROM budgets b
JOIN categories c ON c.id = b.category_id
WHERE b.user_id = $1
AND TO_CHAR(b.month, 'YYYY-MM') = $2
`

type GetBudgetsForMonthParams struct {
	UserID uuid.UUID
	Month  string
}

type GetBudgetsForMonthRow struct {
	CategoryID   uuid.UUID
	CategoryName string
	MonthlyLimit decimal.Decimal
}

func (q *Queries) GetBudgetsForMonth(ctx context.Context, arg GetBudgetsForMonthParams) ([]GetBudgetsForMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, getBudgetsForMonth, arg.UserID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBudgetsForMonthRow
	for rows.Next() {
		var i GetBudgetsForMonthRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.MonthlyLimit); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
