// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_month_spending.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getMonthlySpending = `-- name: GetMonthlySpending :many
SELECT 
    t.category_id,
    SUM(t.amount) AS total_spent
FROM transactions t
JOIN accounts a ON a.id = t.account_id
WHERE a.user_id = $1
AND TO_CHAR(t.occurred_at, 'YYYY-MM') = $2
GROUP BY t.category_id
`

type GetMonthlySpendingParams struct {
	UserID     uuid.UUID
	OccurredAt time.Time
}

type GetMonthlySpendingRow struct {
	CategoryID uuid.UUID
	TotalSpent int64
}

func (q *Queries) GetMonthlySpending(ctx context.Context, arg GetMonthlySpendingParams) ([]GetMonthlySpendingRow, error) {
	rows, err := q.db.QueryContext(ctx, getMonthlySpending, arg.UserID, arg.OccurredAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMonthlySpendingRow
	for rows.Next() {
		var i GetMonthlySpendingRow
		if err := rows.Scan(&i.CategoryID, &i.TotalSpent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
