// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: register_user.sql

package sqlc

import (
	"context"
)

const registerUser = `-- name: RegisterUser :one
INSERT INTO users (id, email, password_hash)
VALUES (
    gen_random_uuid(),
    $1,
    $2
)
RETURNING id, email, password_hash, created_at
`

type RegisterUserParams struct {
	Email        string
	PasswordHash string
}

func (q *Queries) RegisterUser(ctx context.Context, arg RegisterUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, registerUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
