// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_transaction.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET amount = $1, occurred_at = $2, description = $3, account_id = $4, category_id = $5
WHERE id = $6
RETURNING id, amount, created_at, occurred_at, description, account_id, category_id
`

type UpdateTransactionParams struct {
	Amount      string
	OccurredAt  time.Time
	Description sql.NullString
	AccountID   uuid.UUID
	CategoryID  uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Amount,
		arg.OccurredAt,
		arg.Description,
		arg.AccountID,
		arg.CategoryID,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.CreatedAt,
		&i.OccurredAt,
		&i.Description,
		&i.AccountID,
		&i.CategoryID,
	)
	return i, err
}
